import esbuild, { build } from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

function copyArtifactsToDirectory(artifacts, dirpath) {
    console.log("Copying artifacts to dirpath", dirpath);
    try {
        //console.debug("Creating dir", dirpath);
        fs.mkdirSync(dirpath).catch(() => null);
    } catch {
    }
    for (let artifact of artifacts) {
        const outFilepath = path.join(dirpath, artifact);
        //console.debug("copying", artifact, "to", outFilepath);
        fs.copyFileSync(artifact, outFilepath);	
    }
}

function copyArtifactsToVaults(artifacts) {
    if (process.platform != "win32") {
        // XXX configFilePath is only implemented for Win32, other OSs not
        //     supported yet
        console.warn("Copying artifacts to vaults only supported on Windows, copy manually");
        return;
    }
    let configFilepath = path.join(process.env.APPDATA , "obsidian", "obsidian.json");
    let configData = fs.readFileSync(configFilepath, "utf8");
    let config = JSON.parse(configData);

    let manifestData = fs.readFileSync("manifest.json", "utf8");
    let manifest = JSON.parse(manifestData);

    for (let id in config.vaults) {
        let vault = config.vaults[id];
        if (vault.path.endsWith(path.sep + "Obsidian Sandbox")) {
            //console.debug("Ignoring sandbox");
            continue;
        }
        let dirpath = path.join(vault.path, ".obsidian", "plugins",  manifest.id);
        copyArtifactsToDirectory(artifacts, dirpath);
    }
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// JSZip's browser shim resolves "readable-stream" to `require("stream")` so a
// bundler can supply a single stream implementation. This plugin never uses
// JSZip's node stream output (all zip I/O is arraybuffer), and when "stream" is
// left as a runtime require Obsidian warns on mobile ("edit-history attempted
// to load NodeJS package: stream"). Stub the stream modules to an empty object
// so the require is gone from the bundle and the plugin loads clean on mobile.
// JSZip is aliased to its source entry (below) so these requires are visible to
// esbuild rather than baked into JSZip's prebuilt dist.
const stubJszipNodeStream = {
    name: "stub-jszip-node-stream",
    setup(build) {
        build.onResolve({ filter: /^(stream|readable-stream)$/ }, () => ({
            path: "jszip-node-stream-stub",
            namespace: "jszip-node-stream-stub",
        }));
        build.onLoad({ filter: /.*/, namespace: "jszip-node-stream-stub" }, () => ({
            contents: "module.exports = {};",
            loader: "js",
        }));
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    plugins: [stubJszipNodeStream],
    // Bundle JSZip from its source entry, not the prebuilt dist, so the
    // stream-stub plugin above can intercept its readable-stream/stream requires.
    alias: {
        "jszip": path.resolve("node_modules/jszip/lib/index.js"),
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    // Minify production builds: JSZip is now bundled from (unminified) source
    // instead of its prebuilt minified dist, so minifying keeps the artifact
    // small (and smaller than the previous dist-based build).
    minify: prod,
    outfile: "main.js",
});

let artifacts = ["main.js", "manifest.json", "styles.css"];

if (prod) {
    let buildResult = await context.rebuild();
    if ((buildResult.errors.length == 0) && (buildResult.warnings.length == 0)) {
        copyArtifactsToVaults(artifacts);
        
        let manifestData = fs.readFileSync("manifest.json", "utf8");
        let manifest = JSON.parse(manifestData);
        copyArtifactsToDirectory(artifacts, path.join("releases", manifest.version));
    }
    process.exit(0);
} else {
    await context.watch();
}